language: php

php:
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest
  - travis_retry composer global require codeclimate/php-test-reporter

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix
  - vendor/bin/phpstan analyse -c phpstan.neon -l 7 html src tests
  - vendor/bin/psalm

after_script:
  - CODECLIMATE_REPO_TOKEN="ccc827c071779278209c2bbab65069429f0a615bf3b7301ce2e371aa56656f43" test-reporter
