version: '3.6'
services:
  app:
    build:
      context: .
    environment:
      - APP_URL=http://localhost:8000
      - DB_URL=pgsql://postgres:postgres@db/postgres
    ports:
      - 8000:80
  db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
